# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'NPM: Install Task Dependencies'
  inputs:
    workingDir: GenericHtmlReport
    verbose: false

- task: Npm@1
  displayName: 'npm install extension'
  inputs:
    workingDir: .
    verbose: false

- task: Npm@1
  displayName: 'build extension'
  inputs:
    command: custom
    workingDir: .
    verbose: false
    customCommand: 'run build:cidev'

- task: PackageAzureDevOpsExtension@3
  displayName: 'TFX: Package Extension Prod'
  inputs:
    rootFolder: .
    patternManifest: 'vss-extension.json'
    publisherId: LeonardoMoura
    extensionId: azure-pipelines-generic-html-report
    extensionName: 'Generic Html Viewer'
    extensionVisibility: private
    extensionPricing: free
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))

- task: PackageAzureDevOpsExtension@3
  displayName: 'TFX: Package Extension Dev'
  inputs:
    rootFolder: .
    patternManifest: 'vss-extension.json'
    publisherId: LeonardoMoura
    extensionId: azure-pipelines-generic-html-report
    extensionTag: dev
    extensionName: 'Generic Html Viewer Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    updateTasksVersion: true
    extensionVisibility: private
    extensionPricing: free
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'main'))

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()
