# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- script: "npm install -g tfx-cli"

- task: Npm@1
  displayName: 'NPM: Install Task Dependencies'
  inputs:
    workingDir: GenericHtmlReport
    verbose: false

- task: Npm@1
  displayName: 'npm install extension'
  inputs:
    workingDir: .
    verbose: false

- script: "npm run build:cidev"
# - script: "npm run build:cidev"

# - task: TfxInstaller@3
#   displayName: 'Use Node CLI for Azure DevOps'
#   inputs:
#     version: '0.9.x'
#     checkLatest: true

# - task: PackageAzureDevOpsExtension@3
#   displayName: 'Package Extension: $(Build.SourcesDirectory)'
#   name: 'packageStep'
#   inputs:
#     rootFolder: '$(Build.SourcesDirectory)'
#     outputPath: '$(Build.SourcesDirectory)\azure-pipelines-generic-html-report.vsix'
#     publisherId: 'LeonardoMoura'
#     extensionId: 'azure-pipelines-generic-html-report'
#     extensionTag: '-build'
#     extensionName: 'Generic Html Report Dev'
#     extensionVersion: '1.0.$(Build.BuildId)'
#     updateTasksVersion: true
#     updateTasksVersionType: patch
#     extensionVisibility: private
# - task: PublishAzureDevOpsExtension@3
#   name: 'publishDev'
#   inputs:
#     connectTo: 'VsTeam'
#     connectedServiceName: 'LeonardoMouraMarketPlaceSVC'
#     fileType: 'vsix'
#     vsixFile: '$(Build.SourcesDirectory)\azure-pipelines-generic-html-report.vsix'
#     publisherId: 'LeonardoMoura'
#     extensionId: 'azure-pipelines-generic-html-report'
#     extensionTag: dev
#     extensionName: 'Generic Html Report Dev'
#     extensionVersion: '1.0.$(Build.BuildId)'
#     updateTasksVersion: true
#     updateTasksVersionType: patch
#     extensionVisibility: private
#     shareWith: 'leonardosm'
#     noWaitValidation: true

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: 'azure-pipelines-generic-html-report.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()
